---
stages:
  - lint
  - test
  - deploy

lint-job:
  script:
    - npm install
    - npm run lint
  stage: lint
  tags:
    - ex-runner

test-job:
  script:
    - npm install
    - npm run test
  stage: test
  tags:
    - ex-runner

deploy-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - npm install
    - npm run delete
    - npm run init
    - npm run debug
    - npm run start
  stage: deploy
  tags:
    - ex-app
